### ISSUE TITLE
Provide support for .ll and essential bits file parsing

### ISSUE THREAD

**Issue by wirthlin** [byuccl/bfat#14]
Provide support for parsing .ll files and essential bits files so that users can easily identify potential bits that can be analyzed. Users could generate a list of bits to query from these files without doing fault injection or radiation testing.

**Comment by ethanrcampbell02** [comment]
Scripts for these features are added as of commit [3c4061f](https://github.com/byuccl/bfat/commit/3c4061f117f955386056b65fe9bedc2bfcaa7d85).
