### ISSUE TITLE
Update VivadoQuery handling of GND and VCC nets

### ISSUE THREAD

**Issue by JacksonSahleen** [byuccl/bfat#24]
GND and VCC nets change based on the design and need to be handled as such. Develop a way to automatically assess any potential GND/VCC nets and their connections. (Generally, GND/VCC nets end with some form of GND/VCC and may have many names but are all routed the same, but this could potentially be incorrect for some designs)

**Comment by ethanrcampbell02** [comment]
Fixed in commit 5b6bbe4594f7de2d1b4d81790fa7afe4d12c1798
