### ISSUE TITLE
Support Net Tracing to identify PIPs and corresponding bits

### ISSUE THREAD

**Issue by wirthlin** [byuccl/bfat#29]
In our latest BFAT analysis of the VexRiscv Linux system we found that the data lines on the DDR are the largest contributor to faults in our TMR system. It would be nice to "predict" what these bits are and actually count the sensitive bits associated with these nets. To do this, it would be nice to have the ability to trace nets from source to all sinks and return all the PIPs and bits associated with the net so we can get a feel for the sensitivity of the net. This would help us get a feel for how "long" the nets are in terms of CRAM sensitivity.

**Comment by ethanrcampbell02** [comment]
Added script for this function in 98fa49e86a6c992290f4086f74a91b499077dab7
