### ISSUE TITLE
LICENSE file should be full text of the license

### ISSUE THREAD

**Issue by mithro** [byuccl/bfat#8]
The general best practice is to make the LICENSE file the full text of the license and then putting a reference in the README and at the top of files. If you do this, then GitHub should detect this repository is available under an Apache 2.0 license.

You can see examples under https://github.com/chipsalliance and https://github.com/f4pga

**Comment by JacksonSahleen** [comment]
Hey. I got that fixed. Thanks for the heads up! If you see anything wrong with the licensing or anything else, please let us know.
